// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmvfuzprqlthggalehau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtdmZ1enBycWx0aGdnYWxlaGF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzOTE3ODUsImV4cCI6MjA1NTk2Nzc4NX0.0UDKwIK69FCStV6jeHfbTSD7sk0ZKqX47e3X13X1vpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);